version: "3"

services:
  db:
    image: mysql:latest
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    command:
      # 명령어 실행
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: my-password
      MYSQL_DATABASE: xtdb
    restart: always
